### PR TITLE
set tolerance to 0

### PR DESCRIPTION
**Pull request by minmingzhu**
Signed-off-by: minmingz <minming.zhu@inte.com>

### CODE REVIEW

**Comment by xwu99** [comment]
@minmingzhu there is a convergedist param in kmeans.conf, I think it's not used anywhere and may cause confusion, could you consider to remove it ?

**Comment by xwu99** [comment]
> Signed-off-by: minmingz [minming.zhu@inte.com](mailto:minming.zhu@inte.com)

You may consider to add a code comment to explain why you set tolerance to 0.

**Comment by minmingzhu** [comment]
> > Signed-off-by: minmingz [minming.zhu@inte.com](mailto:minming.zhu@inte.com)
> 
> You may consider to add a code comment to explain why you set tolerance to 0.

it's done.

**Comment by minmingzhu** [comment]
> > Signed-off-by: minmingz [minming.zhu@inte.com](mailto:minming.zhu@inte.com)
> 
> You may consider to add a code comment to explain why you set tolerance to 0.

it's done.

**Pull request merged**
