### PR TITLE
Add XGboost classification workload

### PR DESCRIPTION
**Pull request by xwu99**
- Reuse GradientBoostedTreeDataGenerator to generate dataset
- Read dataset and convert to ml.LabeledPoint and to ml.DataFrame
- Call XGBoost and passed in params for training
- Call XGBoost prediction and print test error

XGBoost4J-Spark requires Apache Spark 2.4+

### CODE REVIEW

**Comment by gczsjdy** [comment]
Could you add this in docs?

**Comment by carsonwang** [comment]
why is travis failing ? @xwu99

**Comment by xwu99** [comment]
> why is travis failing ? @xwu99

XGBoost4J-Spark requires Apache Spark 2.4+

**Comment by carsonwang** [comment]
Merge this one first.

**Pull request merged**
