### PR TITLE
Make storage level configurable in kmeans

### PR DESCRIPTION
**Pull request by yeyuqiang**
This PR will add storage level conf in kmeans workloads and make it configurable.
Background for this PR
We are testing some other storage level (customized storage level for Optane PMem). We'd better have configurable interface in kmeans workload.

### CODE REVIEW

**Comment by yeyuqiang** [comment]
@winningsix Please help to review

**Comment by winningsix** [comment]
Which JIRA should I close? @yeyuqiang

**Comment by xwu99** [comment]
There is an issue #621 reported. @yeyuqiang @winningsix I found there is no "hibench.kmeans.storage.level" entry in kmeans.conf, does it make $K_STORAGE_LEVEL null? Could you pls re-check? @carsonwang

**Comment by yeyuqiang** [comment]
> There is an issue #621 reported. @yeyuqiang @winningsix I found there is no "hibench.kmeans.storage.level" entry in kmeans.conf, does it make $K_STORAGE_LEVEL null? Could you pls re-check? @carsonwang

Seems that c.copy(storageLevel = x) is not enough to handle the case when we did not set this entry and defaultParam here is useless. Anyway, we should add "hibench.kmeans.storage.level” entry in kmeans.conf?

**Comment by xwu99** [comment]
@yeyuqiang Have you verified? @winningsix @carsonwang should merge this first and I will rebase my modification #612 on it.

**Comment by yeyuqiang** [comment]
> @yeyuqiang Have you verified? #626 @winningsix @carsonwang should merge this first and I will rebase my modification #612 on it.

Yes, add entry will make hibench kmeans works

**Pull request merged**
